import {fireEvent,render,screen,waitFor,cleanup} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {AdminRecurrenteRefundView} from './AdminRecurrenteRefundView';
import {refundEligibility,requestTotalRefund,verifyRefund,type RefundEligibility} from '@/services/recurrenteRefundService';
import {ApiError} from '@/services/api';
vi.mock('@/components/admin/AdminLayout',()=>({AdminLayout:({children}:{children:React.ReactNode})=><main>{children}</main>}));
vi.mock('@/services/recurrenteRefundService',async importOriginal=>({...await importOriginal<typeof import('@/services/recurrenteRefundService')>(),refundEligibility:vi.fn(),requestTotalRefund:vi.fn(),verifyRefund:vi.fn()}));
const data:RefundEligibility={id_transaccion:800,id_pago:900,id_cuota:1000,id_checkout:700,numero_comprobante:'NXR-00000900',concepto:'HU18 TEST',residente:'Residente TEST',unidad:'B-302',fecha_pago:'2026-10-02',fecha_limite:'2026-10-08',estado:'CONFIRMADA',ambiente:'sandbox',moneda:'GTQ',original_centavos:500,devuelto_centavos:0,reservado_centavos:0,disponible_centavos:500,abono_neto_centavos:500,elegible:true,motivo_inhabilitacion:null,requiere_verificacion_proveedor:true,reembolsos:[]};
const rr={id_reembolso:80,id_transaccion:800,referencia_local:'test',id_externo:'re_TEST',monto_centavos:500,moneda:'GTQ',ambiente:'sandbox',tipo:'TOTAL',estado:'CONFIRMADO' as const,motivo:'Error administrativo TEST',estado_proveedor:'succeeded',error_codigo:null,creado_en:'2026-10-03',fecha_contable:'2026-10-02',aplicado_en:'2026-10-03',evidencia_confirmacion:'POST'};
function start(path='/admin/pagos/reembolsos?transaccion=800'){return render(<MemoryRouter initialEntries={[path]}><AdminRecurrenteRefundView/></MemoryRouter>);}
async function confirm(){await screen.findByText('HU18 TEST · Cuota 1000');fireEvent.change(screen.getByLabelText(/Motivo administrativo/),{target:{value:'Error administrativo TEST'}});fireEvent.click(screen.getByRole('button',{name:'Solicitar reembolso total'}));}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(refundEligibility).mockResolvedValue(data);vi.mocked(requestTotalRefund).mockResolvedValue({result:'processed',refund:rr});vi.mocked(verifyRefund).mockResolvedValue({result:'processed',refund:rr});});
afterEach(cleanup);
describe('HU18 ADMIN reembolso total',()=>{
 it('consulta local muestra importe, comprobante, asociaciones y Sandbox sin POST',async()=>{start();await screen.findByText('HU18 TEST · Cuota 1000');expect(screen.getAllByText(/Sandbox \/ Prueba/).length).toBeGreaterThan(0);expect(screen.getByText(/NXR-00000900/)).toBeTruthy();expect(requestTotalRefund).not.toHaveBeenCalled();});
 it('motivo obligatorio; modal explícito Q5 y cancelar no envía',async()=>{start();await screen.findByText('HU18 TEST · Cuota 1000');expect((screen.getByRole('button',{name:'Solicitar reembolso total'}) as HTMLButtonElement).disabled).toBe(true);await confirm();expect(screen.getByRole('dialog').textContent).toContain('Q5.00 GTQ');fireEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(requestTotalRefund).not.toHaveBeenCalled();});
 it('envía solo motivo/key y previene doble clic/loading',async()=>{let resolve!:(v:{result:string;refund:typeof rr})=>void;vi.mocked(requestTotalRefund).mockImplementation(()=>new Promise(r=>{resolve=r;}));start();await confirm();const button=screen.getByRole('button',{name:'Confirmar solicitud'});fireEvent.click(button);fireEvent.click(button);expect(requestTotalRefund).toHaveBeenCalledTimes(1);expect(screen.getByText('Solicitando…')).toBeTruthy();const args=vi.mocked(requestTotalRefund).mock.calls[0];expect(args[0]).toBe(800);expect(args[1]).toBe('Error administrativo TEST');expect(args[2]).toMatch(/^[a-f0-9-]{36}$/i);resolve({result:'processed',refund:rr});await screen.findByText(/Reembolso Confirmado/);});
 it('resultado incierto ofrece historial sin retry automático ni éxito falso',async()=>{vi.mocked(requestTotalRefund).mockRejectedValue(new ApiError('FAKE_SENSITIVE',503,{code:'REFUND_UNKNOWN'}));vi.mocked(refundEligibility).mockResolvedValueOnce(data).mockResolvedValue({...data,elegible:false,reservado_centavos:500,disponible_centavos:0,motivo_inhabilitacion:'REFUND_BLOCKED',reembolsos:[{...rr,estado:'INCIERTO',aplicado_en:null}]});start();await confirm();fireEvent.click(screen.getByRole('button',{name:'Confirmar solicitud'}));await screen.findByText(/El resultado es incierto/);expect(requestTotalRefund).toHaveBeenCalledTimes(1);expect(verifyRefund).not.toHaveBeenCalled();expect(screen.queryByText('FAKE_SENSITIVE')).toBeNull();await screen.findByText(/Operación bloqueada/);});
 it('FALLIDA no elegible impide solicitar',async()=>{vi.mocked(refundEligibility).mockResolvedValue({...data,estado:'FALLIDA',id_pago:null,elegible:false,motivo_inhabilitacion:'REFUND_INELIGIBLE'});start();await screen.findByText(/Operación no elegible/);expect((screen.getByRole('button',{name:'Solicitar reembolso total'}) as HTMLButtonElement).disabled).toBe(true);});
 it('GET de refund conocido solo tras botón explícito',async()=>{vi.mocked(refundEligibility).mockResolvedValue({...data,elegible:false,reembolsos:[{...rr,estado:'PENDIENTE',aplicado_en:null}]});start();await screen.findByText('Verificar reembolso conocido');expect(verifyRefund).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Verificar reembolso conocido'}));await waitFor(()=>expect(verifyRefund).toHaveBeenCalledWith(80));expect(requestTotalRefund).not.toHaveBeenCalled();});
 it('error de consulta seguro y sin envío financiero',async()=>{vi.mocked(refundEligibility).mockRejectedValue(new ApiError('SENSITIVE_FAKE',403));start();await screen.findByRole('alert');expect(screen.getByRole('alert').textContent).toBe('Acceso exclusivo para administradores.');expect(requestTotalRefund).not.toHaveBeenCalled();});
 it('historial muestra estados individuales y no ofrece void/parcial',async()=>{vi.mocked(refundEligibility).mockResolvedValue({...data,reembolsos:[{...rr,estado:'FALLIDO'}]});start();await screen.findByText(/Reembolso 80 · Fallido/);expect(screen.queryByRole('button',{name:/anular|parcial/i})).toBeNull();});
});
