import type { ReactNode } from 'react';
import { act, fireEvent, render, screen } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import { ApiError } from '@/services/api';
import { listRecurrenteTransactions, verifyRecurrenteTransactions } from '@/services/recurrenteReconciliationService';
import type { ReconciliationResponse } from '@/types/recurrenteReconciliation';
import { AdminRecurrenteReconciliationView } from './AdminRecurrenteReconciliationView';
vi.mock('@/components/admin/AdminLayout',()=>({AdminLayout:({children}:{children:ReactNode})=><main>{children}</main>}));
vi.mock('@/services/recurrenteReconciliationService',async original=>({...await original<typeof import('@/services/recurrenteReconciliationService')>(),listRecurrenteTransactions:vi.fn(),verifyRecurrenteTransactions:vi.fn()}));
const response:ReconciliationResponse={ambiente:'sandbox',alcance:'filtros',verificado:false,completo:true,limite_operaciones:200,resumen:{evaluadas:1,conciliadas:0,diferencias:0,pendientes:1,errores_verificacion:0,sin_fecha:0},exploracion_externa:{solicitada:false,completa:null,motivo:'NO_SOLICITADA'},externas_sin_asociacion:[],operaciones:[{
  clave:'intent:296',id_transaccion:296,id_checkout:433,id_cuota:171,id_pago:395,id_residente:1,residente:'Residente Demo',unidad:'B-302',concepto:'HU13 Sandbox Q5 TEST',referencia_local:'hu17-uuid',numero_comprobante:'NXR-00000395',fecha_operacion:'2026-10-02',sin_fecha_verificable:false,clasificacion:'PENDIENTE',motivo:'SIN_EVIDENCIA_EXTERNA',diferencias:[],faltantes:[],comprobaciones:[],
  interno:{intent_id:'in_fixture',checkout_id:'ch_fixture',pago_externo:'pa_fixture',estado_transaccion:'CONFIRMADA',estado_checkout:'CONFIRMADO',estado_proveedor:'paid',monto_centavos:500,moneda:'GTQ',ambiente:'sandbox',fecha_pago:'2026-10-02'},externo:null,saldo_actual_centavos:0,sobrepago_centavos:0,eventos:[]}]};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(listRecurrenteTransactions).mockResolvedValue(structuredClone(response));vi.mocked(verifyRecurrenteTransactions).mockResolvedValue({...structuredClone(response),verificado:true});});
it('inicio solo consulta registros locales y muestra referencia, clasificación y saldo',async()=>{render(<AdminRecurrenteReconciliationView/>);await screen.findByText('Transacción 296');expect(listRecurrenteTransactions).toHaveBeenCalledWith({});expect(verifyRecurrenteTransactions).not.toHaveBeenCalled();expect(screen.getByText('NXR-00000395')).toBeInTheDocument();expect(screen.getByText('Saldo actual: 0.00 GTQ')).toBeInTheDocument();});
it('loading evita doble clic y al terminar habilita acción',async()=>{
  let resolve!:(r:ReconciliationResponse)=>void;vi.mocked(verifyRecurrenteTransactions).mockReturnValue(new Promise(r=>{resolve=r;}));render(<AdminRecurrenteReconciliationView/>);await screen.findByText('Transacción 296');
  const button=screen.getByRole('button',{name:'Verificar con Recurrente'});fireEvent.click(button);fireEvent.click(button);expect(verifyRecurrenteTransactions).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Verificando con Recurrente…'})).toBeDisabled();expect(screen.getByRole('status')).toHaveTextContent('Verificando operaciones');
  await act(async()=>resolve({...response,verificado:true}));expect(screen.getByRole('button',{name:'Verificar con Recurrente'})).toBeEnabled();
});
it.each(['CONCILIADA','DIFERENCIA','PENDIENTE','ERROR_DE_VERIFICACION'] as const)('muestra clasificación %s con detalle legible',async classification=>{
  const r=structuredClone(response);r.operaciones[0].clasificacion=classification;if(classification==='DIFERENCIA')r.operaciones[0].diferencias=[{codigo:'VALOR_DISTINTO',campo:'intent.monto_centavos',interno:500,externo:600}];
  vi.mocked(verifyRecurrenteTransactions).mockResolvedValue({...r,verificado:true});render(<AdminRecurrenteReconciliationView/>);await screen.findByText('Transacción 296');fireEvent.click(screen.getByRole('button',{name:'Verificar con Recurrente'}));await screen.findByText(/Comparación con Recurrente realizada/);
  const label={CONCILIADA:'Conciliada',DIFERENCIA:'Diferencia',PENDIENTE:'Pendiente',ERROR_DE_VERIFICACION:'Error de verificación'}[classification];expect(screen.getAllByText(label).length).toBeGreaterThan(0);if(classification==='DIFERENCIA')expect(screen.getByText('intent.monto_centavos: interno 500 / externo 600')).toBeInTheDocument();
});
it.each([401,403,500])('error %i seguro sin filtrar payload ni mantener resultado viejo',async status=>{vi.mocked(verifyRecurrenteTransactions).mockRejectedValue(new ApiError('PRIVATE_KEY_SQL',status));render(<AdminRecurrenteReconciliationView/>);await screen.findByText('Transacción 296');fireEvent.click(screen.getByRole('button',{name:'Verificar con Recurrente'}));await screen.findByRole('alert');expect(screen.queryByText('PRIVATE_KEY_SQL')).not.toBeInTheDocument();expect(screen.queryByText('Transacción 296')).not.toBeInTheDocument();});
it('filtros se envían sin monto/moneda/estado financiero editable',async()=>{render(<AdminRecurrenteReconciliationView/>);await screen.findByText('Transacción 296');fireEvent.change(screen.getByLabelText('Residente (ID)'),{target:{value:'1'}});fireEvent.change(screen.getByLabelText('Referencia'),{target:{value:'pa_fixture'}});fireEvent.change(screen.getByLabelText('Estado local'),{target:{value:'FALLIDA'}});fireEvent.click(screen.getByRole('button',{name:'Verificar con Recurrente'}));expect(verifyRecurrenteTransactions).toHaveBeenCalledWith({residente:'1',referencia:'pa_fixture',estado_local:'FALLIDA'},false);});
it('exploración exige período y marca alcance externo parcial, candidatos aparte',async()=>{
  const r=structuredClone(response);r.completo=false;r.exploracion_externa={solicitada:true,completa:false,motivo:'SIN_EVIDENCIA_DE_FIN'};r.externas_sin_asociacion=[{tipo:'intent',id_externo:'in_unassociated',checkout_id:null,estado:'failed',monto_centavos:500,moneda:'GTQ',fecha_operacion:null,clasificacion:'PENDIENTE',motivo:'ASOCIACION_NO_VERIFICADA'}];vi.mocked(verifyRecurrenteTransactions).mockResolvedValue(r);
  render(<AdminRecurrenteReconciliationView/>);await screen.findByText('Transacción 296');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Verificar con Recurrente'}));expect(await screen.findByRole('alert')).toHaveTextContent('Selecciona ambas fechas');expect(verifyRecurrenteTransactions).not.toHaveBeenCalled();
  fireEvent.change(screen.getByLabelText('Desde'),{target:{value:'2026-10-01'}});fireEvent.change(screen.getByLabelText('Hasta'),{target:{value:'2026-10-02'}});fireEvent.click(screen.getByRole('button',{name:'Verificar con Recurrente'}));await screen.findByText(/Exploración externa: parcial/);expect(screen.getByText(/in_unassociated/)).toHaveTextContent('Sin fecha verificable');
});
it('no ofrece acciones para cobrar, confirmar, corregir ni reembolsar',async()=>{render(<AdminRecurrenteReconciliationView/>);await screen.findByText('Transacción 296');for(const name of [/Confirmar/i,/Corregir/i,/Cobrar/i,/Reembolsar/i])expect(screen.queryByRole('button',{name})).not.toBeInTheDocument();});
