import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { getUnifiedAmenityAvailabilityRequest } from "@/services/amenitiesService";
import type { AmenityAvailabilityResponse, AmenityAvailabilitySlot } from "@/types/amenities";
const today=()=>new Date().toISOString().slice(0,10);
export function ResidenteUnifiedAmenitiesAvailabilityView(){const navigate=useNavigate();const[fecha,setFecha]=useState(today());const[data,setData]=useState<AmenityAvailabilityResponse[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selected,setSelected]=useState<{id:number;slot:AmenityAvailabilitySlot}|null>(null);
useEffect(()=>{let active=true;setLoading(true);setError("");setSelected(null);getUnifiedAmenityAvailabilityRequest(fecha).then(r=>{if(active)setData(r.amenidades)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"No fue posible consultar disponibilidad.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[fecha]);
return <AppShell role="residente" title="Disponibilidad general" subtitle="Compara todas las amenidades para una misma fecha."><label className="block max-w-xs text-sm">Fecha<input aria-label="Fecha" type="date" value={fecha} min={today()} onChange={e=>setFecha(e.target.value)} className="mt-1 w-full rounded-md border p-2"/></label>{error?<p className="mt-4 bg-rose-50 p-3 text-rose-700">{error}</p>:null}{loading?<p className="mt-4">Cargando disponibilidad...</p>:<div className="mt-5 grid gap-4 lg:grid-cols-2">{data.map(item=><section key={item.amenidad.id_amenidad} className="rounded-xl border bg-white p-4"><h2 className="font-semibold">{item.amenidad.nombre}</h2><p className="text-sm text-slate-500">{item.amenidad.hora_apertura}–{item.amenidad.hora_cierre}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{item.slots.map(slot=><button key={slot.hora_inicio} disabled={!slot.disponible} onClick={()=>setSelected({id:item.amenidad.id_amenidad,slot})} className={`rounded-lg border p-2 text-sm ${slot.disponible?selected?.id===item.amenidad.id_amenidad&&selected.slot.hora_inicio===slot.hora_inicio?"border-blue-500 bg-blue-50":"bg-emerald-50 text-emerald-700":"cursor-not-allowed bg-rose-50 text-rose-700"}`}><span>{slot.hora_inicio}–{slot.hora_fin}</span><small className="block">{slot.disponible?"Disponible":"Ocupado"}</small></button>)}</div></section>)}</div>}<div className="mt-5 flex justify-end"><Button disabled={!selected} onClick={()=>selected&&navigate(`/residente/amenidades?amenidad=${selected.id}&fecha=${fecha}&inicio=${selected.slot.hora_inicio}&fin=${selected.slot.hora_fin}`)}>Continuar a reservar</Button></div></AppShell>}
