const PDFDocument=require("pdfkit"),ExcelJS=require("exceljs"),{query}=require("../database/mysql");
const REPORTS={accesos:"SELECT a.fecha,v.nombre visitante,a.tipo_visita tipo,a.estado_acceso estado FROM ACCESO a JOIN VISITANTE v ON v.id_visitante=a.id_visitante",reservas:"SELECT r.fecha,u.nombre usuario,am.nombre amenidad,r.estado FROM RESERVA r JOIN USUARIO u ON u.id_usuario=r.id_usuario JOIN AMENIDAD am ON am.id_amenidad=r.id_amenidad",morosos:"SELECT cu.fecha_limite fecha,u.nombre residente,c.numero unidad,cu.monto FROM CUOTA cu JOIN CASA c ON c.id_casa=cu.id_casa JOIN RESIDENTE r ON r.id_residente=c.id_residente JOIN USUARIO u ON u.id_usuario=r.id_usuario WHERE cu.fecha_limite<CURDATE()",sanciones:"SELECT s.fecha_generacion fecha,u.nombre residente,s.motivo,s.monto,s.estado FROM SANCION s JOIN CASA c ON c.id_casa=s.id_casa JOIN RESIDENTE r ON r.id_residente=c.id_residente JOIN USUARIO u ON u.id_usuario=r.id_usuario"};
function validate(type,format){if(!REPORTS[type])throw Object.assign(new Error("Reporte inválido."),{status:400});if(!["pdf","xlsx"].includes(format))throw Object.assign(new Error("Formato inválido."),{status:400});return{type,format};}
function validateFilters(i={}){const desde=String(i.desde||""),hasta=String(i.hasta||"");for(const v of[desde,hasta])if(v&&!/^\d{4}-\d{2}-\d{2}$/.test(v))throw Object.assign(new Error("Fecha de reporte inválida."),{status:400});if(desde&&hasta&&desde>hasta)throw Object.assign(new Error("El rango del reporte es inválido."),{status:400});return{desde,hasta};}
function safe(v){const s=String(v??"");return/^[=+\-@]/.test(s)?`'${s}`:s}
async function rows(type,input={}){const f=validateFilters(input),w=[],p=[];if(f.desde){w.push("DATE(reporte.fecha)>=?");p.push(f.desde)}if(f.hasta){w.push("DATE(reporte.fecha)<=?");p.push(f.hasta)}return query(`SELECT * FROM (${REPORTS[type]}) reporte ${w.length?`WHERE ${w.join(" AND ")}`:""} ORDER BY reporte.fecha DESC LIMIT 500`,p)}
async function excel(type,data,user,f={}){const w=new ExcelJS.Workbook(),s=w.addWorksheet("Reporte"),keys=Object.keys(data[0]||{sin_datos:""});s.addRow([`Reporte ${type}`,`Generado por ${user}`,new Date().toISOString(),`Período ${f.desde||"inicio"} a ${f.hasta||"actual"}`]);s.addRow(keys);for(const r of data)s.addRow(keys.map(k=>safe(r[k])));return Buffer.from(await w.xlsx.writeBuffer())}
function pdf(type,data,user,f={}){return new Promise((resolve,reject)=>{const d=new PDFDocument({margin:40}),chunks=[];d.on("data",c=>chunks.push(c));d.on("end",()=>resolve(Buffer.concat(chunks)));d.on("error",reject);d.fontSize(18).text(`Reporte ${type}`);d.fontSize(10).text(`Generado: ${new Date().toISOString()} · Usuario: ${user} · Período: ${f.desde||"inicio"} a ${f.hasta||"actual"}`);for(const r of data)d.moveDown(.5).text(Object.entries(r).map(([k,v])=>`${k}: ${safe(v)}`).join(" | "));d.end()})}
module.exports={validate,validateFilters,safe,rows,excel,pdf};
