const FINANCIAL_TABLES = [
  "PAGO_ORIGEN", "CHECKOUT_RECURRENTE", "TRANSACCION_RECURRENTE", "EVENTO_RECURRENTE", "REEMBOLSO_RECURRENTE",
  "INTENTO_RECURRENTE", "REVISION_EVENTO_RECURRENTE", "REPARACION_REVISION_RECURRENTE",
];
const REQUIRED_FINANCIAL_TABLES = ["CUOTA", "PAGO", "RECARGO_APLICADO", "TRANSACCION_SIMULADA", ...FINANCIAL_TABLES];
// Preserve every previously exported table and include the accounting dependencies.
const BACKUP_TABLES = [
  "TIPO_USUARIO", "USUARIO", "CASA", "RESIDENTE", "INQUILINO", "AMENIDAD", "CUOTA", "PAGO",
  "RESERVA", "VISITANTE", "ACCESO", "REGISTRO_ACCESO", "CONFIGURACION",
  "SERVICIO", "CASA_SERVICIO", "INQUILINO_CASA", "RECARGO_APLICADO", "TRANSACCION_SIMULADA", ...FINANCIAL_TABLES,
];
module.exports = { FINANCIAL_TABLES, REQUIRED_FINANCIAL_TABLES, BACKUP_TABLES };
